# Generated by Django 2.0.6 on 2018-07-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Longevity token', max_length=200)),
                ('text', models.TextField()),
                ('picture', models.ImageField(help_text='Upload image 250x450', upload_to='imgs/other/')),
                ('white_paper_url', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'AboutContent',
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('fullname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to='imgs/teammates/')),
                ('linkedin_url', models.CharField(blank=True, max_length=100)),
                ('github_url', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='docs/about/')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainSectionSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='imgs/slides/')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(max_length=100)),
                ('time_to_begin', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reached', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('background_photo', models.ImageField(upload_to='imgs/news/')),
                ('logo_svg', models.ImageField(upload_to='imgs/logos/')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('native_news', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='page.Page')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('header', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='imgs/partners/')),
                ('url', models.CharField(max_length=100)),
                ('url_text', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SideSocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(max_length=400)),
                ('icon', models.ImageField(upload_to='imgs/side_icons/')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.FileField(upload_to='imgs/icons/')),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('fullname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to='imgs/teammates/')),
                ('linkedin_url', models.CharField(blank=True, max_length=100)),
                ('github_url', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('background_span', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('google_play_url', models.CharField(max_length=200)),
                ('apple_store_url', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'VideoBlock',
            },
        ),
    ]
