# Generated by Django 2.0.2 on 2018-02-20 14:17

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=landing.models.max_value_default, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['line_no'],
            },
        ),
    ]
