# Generated by Django 2.0.7 on 2018-07-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180706_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBlock',
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='MainSectionSlide',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='SideSocialIcon',
        ),
        migrations.DeleteModel(
            name='SocialIcon',
        ),
        migrations.DeleteModel(
            name='Teammate',
        ),
        migrations.DeleteModel(
            name='VideoBlock',
        ),
    ]
