# Generated by Django 2.0.2 on 2018-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('eth_addr', models.CharField(max_length=100, unique=True, verbose_name='etherium account address')),
                ('tokens_amount', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
            ],
            options={
                'db_table': 'investors',
                'ordering': ['id'],
            },
        ),
    ]
