# Generated by Django 2.0.2 on 2018-02-27 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('ETH', 'Ethereum')], max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('amount_wo_bonus', models.DecimalField(decimal_places=8, max_digits=32)),
                ('charged_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'deposits',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('eth_account', models.CharField(max_length=100, unique=True, verbose_name='etherium account address')),
                ('tokens_amount', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
            ],
            options={
                'db_table': 'investors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('ETH', 'Ethereum')], max_length=10)),
                ('txn_id', models.CharField(max_length=100)),
                ('account_to', models.CharField(max_length=100)),
                ('account_from', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('txn_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAIT', 'Wait confirmation')], default='WAIT', max_length=10)),
                ('confirms', models.PositiveIntegerField(default=0)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mint_log',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('bonus_percents', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'phases',
                'ordering': ['begin_date'],
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='user_office.Investor'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit', to='user_office.Mint'),
        ),
        migrations.AddField(
            model_name='account',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_accounts', to='user_office.Investor'),
        ),
    ]
