# Generated by Django 2.0.2 on 2018-04-10 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools
import ico_portal.utils.datetime
import user_office.models.fields
import user_office.models.kyc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('ETH', 'Ethereum')], max_length=10)),
                ('address', user_office.models.fields.EthAddressField(max_length=42)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('amount_wo_bonus', models.DecimalField(decimal_places=8, max_digits=32)),
                ('created_at', models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow)),
                ('charged_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PREPARED', 'Prepared')], default='PREPARED', max_length=10)),
            ],
            options={
                'db_table': 'deposits',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('eth_account', user_office.models.fields.EthAddressField(blank=True, max_length=42, null=True, unique=True, verbose_name='ethereum account address')),
                ('tokens_amount', user_office.models.fields.TokenField(decimal_places=2, default=0, max_digits=63)),
                ('date_joined', models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow)),
                ('referral_id', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(16,), **{}), max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_office.Investor')),
            ],
            options={
                'db_table': 'investors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('WAITING', 'Waiting for approval'), ('DECLINED', 'Declined'), ('APPROVED', 'Approved')], default='WAITING', max_length=10)),
                ('firstname', models.CharField(max_length=30)),
                ('midname', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('document_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('photo',), **{}))),
                ('selfie', models.ImageField(upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('selfie',), **{}))),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('approve_txn_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='user_office.Investor')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
                'db_table': 'kyc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('ETH', 'Ethereum')], max_length=10)),
                ('txn_hash', models.CharField(max_length=100)),
                ('account_to', models.CharField(max_length=100)),
                ('account_from', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAIT', 'Wait confirmation')], default='WAIT', max_length=10)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mint_log',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('bonus_percents', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'phases',
                'ordering': ['begin_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='mint',
            unique_together={('currency', 'txn_hash')},
        ),
        migrations.AddField(
            model_name='deposit',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='user_office.Investor'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit', to='user_office.Mint'),
        ),
        migrations.AddField(
            model_name='account',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_accounts', to='user_office.Investor'),
        ),
    ]
