# Generated by Django 2.0.2 on 2018-02-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='eth_addr',
            new_name='eth_account',
        ),
    ]
