# Generated by Django 2.0.2 on 2018-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
