# Generated by Django 2.0.2 on 2018-05-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='value',
            new_name='amount',
        ),
    ]
