# Generated by Django 2.0.7 on 2018-07-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_auto_20180717_1522'),
        ('user_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc', to='helpdesk.Ticket'),
        ),
    ]
