# Generated by Django 2.0.2 on 2018-03-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mint',
            old_name='txn_id',
            new_name='block_hash',
        ),
        migrations.RemoveField(
            model_name='mint',
            name='confirm_date',
        ),
        migrations.RemoveField(
            model_name='mint',
            name='confirms',
        ),
        migrations.AddField(
            model_name='mint',
            name='block_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mint',
            name='txn_hash',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('Ethereum', 'ETH')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mint',
            name='currency',
            field=models.CharField(choices=[('Ethereum', 'ETH')], max_length=10),
        ),
    ]
