# Generated by Django 2.0.2 on 2018-04-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_office.Investor'),
        ),
    ]
