# Generated by Django 2.0.2 on 2018-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0002_auto_20180410_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(choices=[('ID', 'ID'), ('Passport', 'Passport'), ('DriveLicence', 'Driver Licence'), ('Other', 'Other')], default='Passport', max_length=10),
            preserve_default=False,
        ),
    ]
