# Generated by Django 2.0.2 on 2018-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0002_auto_20180504_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
