# Generated by Django 2.0.2 on 2018-03-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0002_auto_20180301_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mint',
            name='txn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
