# Generated by Django 2.0.6 on 2018-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0002_auto_20180620_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
