
# Generated by Django 2.0.7 on 2018-07-18 14:21

from django.db import migrations, models
import ico_portal.utils.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0002_kyc_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='POUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow)),
                ('oracle_rate', models.DecimalField(decimal_places=0, max_digits=65)),
                ('actual_rate', models.DecimalField(decimal_places=0, max_digits=65)),
                ('txn_id', models.UUIDField()),
            ],
            options={
                'db_table': 'po_update_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='rate_cents',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=32),
            preserve_default=False,
        ),
    ]
