# Generated by Django 2.0.6 on 2018-06-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_ticket_reporter'),
        ('user_office', '0003_investor_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc', to='helpdesk.Ticket'),
        ),
    ]
