# Generated by Django 2.0.2 on 2018-04-16 21:20

from django.db import migrations, models
import ico_portal.utils.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0003_kyc_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICO_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow)),
                ('usd_c_per_eth', models.PositiveIntegerField()),
                ('total_raised', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ico_info',
                'ordering': ['creation_date'],
            },
        ),
    ]
