# Generated by Django 2.0.2 on 2018-03-12 19:20

from django.db import migrations
import user_office.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0003_auto_20180301_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='eth_account',
            field=user_office.models.common.EthAddressField(max_length=42, unique=True, verbose_name='etherium account address'),
        ),
    ]
