# Generated by Django 2.0.7 on 2018-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0003_auto_20180718_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
