# Generated by Django 2.0.2 on 2018-02-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0003_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='username',
            new_name='name',
        ),
    ]
