# Generated by Django 2.0.2 on 2018-05-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0003_auto_20180507_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='account_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
