# Generated by Django 2.0.6 on 2018-06-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0004_kyc_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc', to='helpdesk.Ticket'),
        ),
    ]
