# Generated by Django 2.0.7 on 2018-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0004_auto_20180718_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='poupdate',
            name='new_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=65),
            preserve_default=False,
        ),
    ]
