# Generated by Django 2.0.2 on 2018-03-12 19:29

from django.db import migrations
import user_office.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0004_auto_20180312_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=user_office.models.common.EthAddressField(max_length=42),
        ),
    ]
