# Generated by Django 2.0.2 on 2018-05-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0004_auto_20180508_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(choices=[('ID', 'ID'), ('Passport', 'Passport'), ('DriveLicence', 'Driver Licence'), ('Other', 'Other')], max_length=50),
        ),
    ]
