# Generated by Django 2.0.2 on 2018-04-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0004_ico_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ico_info',
            old_name='total_raised',
            new_name='total_supply',
        ),
    ]
