# Generated by Django 2.0.2 on 2018-02-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0004_auto_20180222_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
