# Generated by Django 2.0.2 on 2018-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0005_auto_20180418_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico_info',
            name='total_supply',
            field=models.DecimalField(decimal_places=0, max_digits=65),
        ),
    ]
