# Generated by Django 2.0.2 on 2018-05-17 14:39

from django.db import migrations, models
import ico_portal.utils.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0005_auto_20180515_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsProcessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow)),
                ('filter_id', models.IntegerField()),
                ('start_block', models.IntegerField()),
                ('end_block', models.IntegerField()),
            ],
            options={
                'db_table': 'events_processing',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ico_info',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='ico_info',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
