# Generated by Django 2.0.7 on 2018-07-20 12:01

from django.db import migrations, models
import functools
import user_office.models.kyc


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0005_poupdate_new_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='city',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='country',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_country',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_date',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_no',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_photo',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='midname',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='registration_address',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='user_photo',
        ),
        migrations.AddField(
            model_name='kyc',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='basis_doc',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('basis',), **{}), verbose_name='Basis for representation'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='beneficial_birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Beneficial date of birth'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='beneficial_fullname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Beneficial fullname'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='beneficial_personal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beneficial personal identification code'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='beneficial_place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beneficial place of birth'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='beneficial_place_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficial place of residence'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='bill_photo',
            field=models.ImageField(default=1, upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('bill_photo',), **{}), verbose_name='Utility bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='business_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Business name'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='director_firstname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First name of director'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='director_lastname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name of director'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='field_of_activity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field of activity'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_document_photo',
            field=models.ImageField(default=1, upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('doc_photo',), **{}), verbose_name='Copy of identification document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='is_pep',
            field=models.NullBooleanField(verbose_name='Politically exposed person (PEP)'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='personal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal identification code'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of residence'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Profession of field of activity'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of registration'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration number'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='type',
            field=models.CharField(choices=[('NATURAL', 'Natural Person'), ('LEGAL', 'Legal Person')], default='NATURAL', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyc',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
    ]
