# Generated by Django 2.0.2 on 2018-03-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0005_auto_20180312_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mint',
            unique_together={('currency', 'txn_hash')},
        ),
    ]
