# Generated by Django 2.0.2 on 2018-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0005_auto_20180222_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='bonus_percents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
