# Generated by Django 2.0.2 on 2018-05-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0006_auto_20180517_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsprocessing',
            old_name='end_block',
            new_name='from_block',
        ),
        migrations.RenameField(
            model_name='eventsprocessing',
            old_name='start_block',
            new_name='last_processed_block',
        ),
        migrations.AlterField(
            model_name='eventsprocessing',
            name='filter_id',
            field=models.CharField(max_length=100),
        ),
    ]
