# Generated by Django 2.0.2 on 2018-02-22 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0006_phase_bonus_percents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='bonus_percents',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
