# Generated by Django 2.0.2 on 2018-04-28 15:45

from django.db import migrations, models
import ico_portal.utils.datetime
import user_office.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0006_auto_20180419_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', user_office.models.fields.CurrencyField(max_length=5)),
                ('creation_date', models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=32)),
                ('timestamp', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['creation_date'],
            },
        ),
    ]
