# Generated by Django 2.0.2 on 2018-03-13 14:44

from django.db import migrations, models
import django.db.models.deletion
import user_office.models.kyc


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0006_auto_20180312_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('WAITING', 'Waiting for approval'), ('DECLINED', 'Declined'), ('APPROVED', 'Approved')], max_length=10)),
                ('firstname', models.CharField(max_length=30)),
                ('midname', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('document_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=user_office.models.kyc.kyc_photo_path)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='user_office.Investor')),
            ],
            options={
                'db_table': 'kyc',
                'ordering': ['id'],
            },
        ),
    ]
