# Generated by Django 2.0.2 on 2018-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0007_auto_20180517_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsprocessing',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='eventsprocessing',
            name='last_processed_block',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
