# Generated by Django 2.0.7 on 2018-07-23 12:55

from django.db import migrations, models
import functools
import user_office.models.kyc


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0007_auto_20180721_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='bill_photo',
            field=models.FileField(upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('bill_photo',), **{}), verbose_name='Utility bill'),
        ),
    ]
