# Generated by Django 2.0.2 on 2018-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0007_kyc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['id'], 'verbose_name': 'KYC', 'verbose_name_plural': 'KYCs'},
        ),
        migrations.AddField(
            model_name='kyc',
            name='country',
            field=models.CharField(default='Russia', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyc',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for approval'), ('DECLINED', 'Declined'), ('APPROVED', 'Approved')], default='WAITING', max_length=10),
        ),
    ]
