# Generated by Django 2.0.2 on 2018-05-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0008_auto_20180517_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsprocessing',
            options={},
        ),
        migrations.RenameField(
            model_name='eventsprocessing',
            old_name='created_at',
            new_name='last_update_at',
        ),
    ]
