# Generated by Django 2.0.7 on 2018-07-25 14:30

from django.db import migrations, models
import django.db.models.deletion
import user_office.models.kyc


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0008_auto_20180723_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('basis_doc', 'Basis for representation'), ('id_document_photo', 'Copy of identification document'), ('bill_photo', 'Utility bill')], max_length=30)),
                ('file', models.FileField(max_length=1000, upload_to=user_office.models.kyc.kyc_attachment_path, verbose_name='File')),
                ('filename', models.CharField(max_length=1000, verbose_name='Filename')),
                ('mime_type', models.CharField(max_length=255, verbose_name='MIME Type')),
                ('size', models.IntegerField(help_text='Size of this file in bytes', verbose_name='Size')),
            ],
            options={
                'db_table': 'kyc_attachments',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='basis_doc',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='bill_photo',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='id_document_photo',
        ),
        migrations.AddField(
            model_name='kycattachment',
            name='kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_office.KYC'),
        ),
    ]
