# Generated by Django 2.0.2 on 2018-03-26 18:16

from django.db import migrations, models
import user_office.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0009_mint_confirmation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='craeted_at',
            field=models.DateTimeField(default=user_office.datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='deposit',
            name='state',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PREPARED', 'Prepared')], default='PREPARED', max_length=10),
        ),
    ]
