# Generated by Django 2.0.6 on 2018-08-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0009_auto_20180725_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_contract', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='kycattachment',
            name='kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='user_office.KYC'),
        ),
    ]
