# Generated by Django 2.0.2 on 2018-05-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0009_auto_20180521_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensmove',
            name='investor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deposits', to='user_office.Investor', to_field='eth_account'),
        ),
    ]
