# Generated by Django 2.0.7 on 2018-07-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0009_auto_20180725_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycattachment',
            name='kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='user_office.KYC'),
        ),
    ]
