# Generated by Django 2.0.2 on 2018-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0010_auto_20180326_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='charged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mint',
            name='block_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mint',
            name='block_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
