# Generated by Django 2.0.7 on 2018-08-03 17:13

import django.core.validators
from django.db import migrations
import user_office.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0010_auto_20180801_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycattachment',
            name='file',
            field=user_office.models.fields.DocFileField(upload_to=user_office.models.fields.hashed_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf', 'doc', 'docx', 'zip'])]),
        ),
    ]
