# Generated by Django 2.0.7 on 2018-08-16 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ico_portal.utils.datetime
import user_office.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0011_auto_20180803_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', user_office.models.fields.TokenField(decimal_places=0, max_digits=65)),
                ('is_from_referrer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow)),
                ('state', models.CharField(choices=[('created', 'Created'), ('accrued', 'Accrued')], default='created', max_length=10)),
                ('accrued_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to='user_office.TokensMove')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to=settings.AUTH_USER_MODEL)),
                ('created_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to='user_office.Payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
