# Generated by Django 2.0.2 on 2018-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0011_auto_20180326_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mint',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
