# Generated by Django 2.0.2 on 2018-05-23 18:04

from django.db import migrations
import user_office.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0011_auto_20180521_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='hard_cap',
            field=user_office.models.fields.TokenField(decimal_places=0, default=100000000000000, max_digits=65),
            preserve_default=False,
        ),
    ]
