# Generated by Django 2.0.2 on 2018-05-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0012_phase_hard_cap'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokensmove',
            table='tokens_moves',
        ),
    ]
