# Generated by Django 2.0.2 on 2018-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0012_auto_20180326_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('ETH', 'Ethereum')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mint',
            name='currency',
            field=models.CharField(choices=[('ETH', 'Ethereum')], max_length=10),
        ),
    ]
