# Generated by Django 2.0.7 on 2018-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0012_referralbonus'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['creation_date', 'currency'], name='exchange_ra_creatio_c15d39_idx'),
        ),
    ]
