# Generated by Django 2.0.2 on 2018-05-30 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0013_auto_20180523_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='photo',
            new_name='document_photo',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='selfie',
            new_name='user_photo',
        ),
        migrations.AddField(
            model_name='kyc',
            name='city',
            field=models.CharField(default='Moscow', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='document_date',
            field=models.DateField(default=datetime.date(2018, 5, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='postcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='registration_address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
    ]
