# Generated by Django 2.0.7 on 2018-08-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0013_auto_20180823_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate_cents',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
    ]
