# Generated by Django 2.0.2 on 2018-03-28 16:56

from django.db import migrations, models
import user_office.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0013_auto_20180327_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='date_joined',
            field=models.DateTimeField(default=user_office.datetime.datetime.utcnow),
        ),
    ]
