# Generated by Django 2.0.2 on 2018-03-29 21:35

from django.db import migrations, models
import user_office.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0014_investor_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(default='kyc/13/828675284204a887713639e1e7fb42e2.jpg', upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investor',
            name='eth_account',
            field=user_office.models.common.EthAddressField(max_length=42, unique=True, verbose_name='ethereum account address'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='photo',
            field=models.ImageField(upload_to=None),
        ),
    ]
