# Generated by Django 2.0.2 on 2018-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0014_auto_20180530_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='document_country',
            field=models.CharField(default='Russia', max_length=50),
            preserve_default=False,
        ),
    ]
