# Generated by Django 2.0.7 on 2018-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0014_auto_20180823_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralbonus',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('prepared', 'Prepared'), ('accrued', 'Accrued')], default='created', max_length=10),
        ),
        migrations.AlterModelTable(
            name='bonus',
            table='bonuses',
        ),
        migrations.AlterModelTable(
            name='referralbonus',
            table='referral_bonuses',
        ),
    ]
