# Generated by Django 2.0.2 on 2018-03-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0015_auto_20180329_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
