# Generated by Django 2.0.6 on 2018-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0015_auto_20180820_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, choices=[('PASS_KYC', 'pass kyc')], default=None, max_length=10, null=True),
        ),
    ]
