# Generated by Django 2.0.2 on 2018-03-30 20:56

from django.db import migrations, models
import functools
import user_office.models.kyc


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0016_auto_20180330_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='approve_txn_hash',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='photo',
            field=models.ImageField(upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *(), **{'prefix': 'photo'})),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *(), **{'prefix': 'selfie'})),
        ),
    ]
