# Generated by Django 2.0.2 on 2018-04-02 15:33

from django.db import migrations, models
import functools
import user_office.models.common
import user_office.models.kyc


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0017_auto_20180330_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='eth_account',
            field=user_office.models.common.EthAddressField(blank=True, max_length=42, null=True, unique=True, verbose_name='ethereum account address'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='photo',
            field=models.ImageField(upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('photo',), **{})),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(upload_to=functools.partial(user_office.models.kyc.kyc_photo_path, *('selfie',), **{})),
        ),
    ]
