# Generated by Django 2.0.2 on 2018-04-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0018_auto_20180402_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='approve_txn_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
