# Generated by Django 2.0.9 on 2018-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0019_auto_20181218_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, choices=[('PASS_KYC', 'pass kyc'), ('CREATE_MEDIATOR', 'create tokens mediator contract')], default=None, max_length=30, null=True),
        ),
    ]
