# Generated by Django 2.0.9 on 2018-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0020_auto_20181218_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
