# Generated by Django 2.0.9 on 2018-12-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0021_auto_20181218_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='deploy_txn_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for approval'), ('DEPLOYING', 'Deploying mediator contract'), ('DECLINED', 'Declined'), ('APPROVED', 'Approved')], default='WAITING', max_length=10),
        ),
    ]
