# Generated by Django 2.0.9 on 2018-12-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0023_auto_20181220_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensmove',
            name='investor',
            field=models.ForeignKey(db_column='investor_account', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tokens_moves', to=settings.AUTH_USER_MODEL, to_field='eth_account'),
        ),
    ]
