export const GET_BOUNTIES_BALANCE_REQUEST = "GET_DEPOSITE_REQUEST"
export const GET_BOUNTIES_BALANCE_SUCCESS = "GET_DEPOSITE_SUCCESS"
export const GET_BOUNTIES_BALANCE_FAILED = 'GET_BOUNTIES_BALANCE_FAILED'

export const TRANSFER_BOUNTIES_REQUEST = "TRANSFER_BOUNTIES_REQUEST"
export const TRANSFER_BOUNTIES_SUCCESS = "TRANSFER_BOUNTIES_SUCCESS"
export const TRANSFER_BOUNTIES_FAILED = "TRANSFER_BOUNTIES_FAILED"


