export const GET_DEPOSITS_REQUEST = "GET_DEPOSITS_REQUEST"
export const GET_DEPOSITS_SUCCESS = "GET_DEPOSITS_SUCCESS"
export const GET_DEPOSITE_FAILED = "GET_DEPOSITE_FAILED"

export const CREATE_PREPARED_DEPOSIT_REQUEST = "CREATE_PREPARED_DEPOSIT_REQUEST"
export const CREATE_PREPARED_DEPOSIT_SUCCESS = "CREATE_PREPARED_DEPOSIT_SUCCESS"
export const CREATE_PREPARED_DEPOSIT_FAILED = "CREATE_PREPARED_DEPOSIT_FAILED"

export const DEPOSITS_NEXT_PAGE = "DEPOSITS_NEXT_PAGE"
export const DEPOSITS_PREV_PAGE = "DEPOSITS_PREV_PAGE"
