export const SHOW_INVEST_FORM = 'SHOW_INVEST_FORM'
export const HIDE_INVEST_FORM = 'HIDE_INVEST_FORM'
export const SEND_TRANSACTION_INIT = 'SEND_TRANSACTION_INIT'
export const SEND_TRANSACTOIN_SUCCESSFULL = 'SEND_TRANSACTOIN_SUCCESSFULL'
