export const GET_KYC_REQUEST = "GET_KYC_REQUEST"
export const GET_KYC_SUCCESSFULL = "GET_KYC_SUCCESSFULL"

export const SUBMIT_KYC_REQUEST = 'SUBMIT_KYC_REQUEST'
export const SUBMIT_KYC_SUCCESSFULL = 'SUBMIT_KYC_SUCCESSFULL'
export const SUBMIT_KYC_FAILED = 'SUBMIT_KYC_FAILED'

export const SUBMIT_AND_GET_KYC_REQEUST = "SUBMIT_AND_GET_KYC_REQEUST"

export const SHOW_KYC_FORM = 'SHOW_KYC_FORM'
export const HIDE_KYC_FORM = 'HIDE_KYC_FORM'
