export const GET_REFERAL_LINK_REQUEST = "GET_REFERAL_LINK_REQUEST" 
export const GET_REFERAL_LINK_SUCCESS = "GET_REFERAL_LINK_SUCCESS" 
export const GET_REFERAL_LINK_FAILED = "GET_REFERAL_LINK_FAILED" 
