export const GET_REFERRAL_LINK_REQUEST = "GET_REFERRAL_LINK_REQUEST"
export const GET_REFERRAL_LINK_SUCCESS = "GET_REFERRAL_LINK_SUCCESS"
export const GET_REFERRAL_LINK_FAILED = "GET_REFERRAL_LINK_FAILED"
