export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESSFULL = "GET_USER_SUCCESSFULL"

export const SHOW_SET_ACCOUNT_FORM = "SHOW_SET_ACCOUNT_FORM"
export const HIDE_SET_ACCOUNT_FORM = "HIDE_SET_ACCOUNT_FORM"

export const SET_ACCOUNT_REQUEST = "SET_ACCOUNT_REQUEST"
export const SET_ACCOUNT_SUCCESSFULL = "SET_ACCOUNT_SUCCESSFULL"

export const SET_METAMASK_ACCOUNT = "SET_METAMASK_ACCOUNT"
