export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESSFULL = "GET_USER_SUCCESSFULL"
export const GET_USER_FAILED = "GET_USER_FAILED"

export const SET_ACCOUNT_REQUEST = "SET_ACCOUNT_REQUEST"
export const SET_ACCOUNT_SUCCESSFULL = "SET_ACCOUNT_SUCCESSFULL"
export const SET_ACCOUNT_FAILED = "SET_ACCOUNT_FAILED"

export const SET_GENERETED_ETHEREUM_ACCOUNT = "SET_GENERETED_ETHEREUM_ACCOUNT"
export const EXTRACT_EXISTING_METAMASK_ACCOUNT = "EXTRACT_EXISTING_METAMASK_ACCOUNT"

export const SET_METAMASK_ACCOUNT_SUCCESSFULL = "SET_METAMASK_ACCOUNT_SUCCESSFULL"
export const SET_METAMASK_ACCOUNT_FAILED = "SET_METAMASK_ACCOUNT_FAILED"

export const DETECT_METAMASK_ACCOUT = "DETECT_METAMASK_ACCOUT"
